### ISSUE TITLE
Where is the source of truth for AllowanceSemaphore, smart pointers and other utils?

### ISSUE THREAD

**Issue by stupaq-fb** [ReactiveSocket/reactive-streams-cpp#1]
There https://github.com/ReactiveSocket/reactivesocket-cpp/blob/master/reactivesocket-cpp/src/streams/AllowanceSemaphore.h or there
https://github.com/ReactiveSocket/reactive-streams-cpp/blob/master/src/utilities/AllowanceSemaphore.h?

**Comment by lehecka** [comment]
it should be definitely here.
reactive-socket-cpp/utilities/AllowanceSemaphore.h

I will fix this

**Comment by stupaq-fb** [comment]
Thanks @lehecka!
